DROP TABLE IF EXISTS MEMBERS;
DROP TABLE IF EXISTS LOBBY;

CREATE TABLE LOBBY (
  ID INT IDENTITY PRIMARY KEY,
  NAME VARCHAR(20) NOT NULL,
  ENTRY_FEES INT NOT NULL,
  MAX_MEMBERS INT NOT NULL,
  PRIZE_MONEY INT NOT NULL,
  LOBBY_CHARGES INT NOT NULL,
  ACTIVE_MEMBERS INT NOT NULL,
  WINNER VARCHAR(20),
  STATUS VARCHAR(5) NOT NULL
);

CREATE TABLE MEMBERS (
  ID INT IDENTITY PRIMARY KEY,
  LOBBY_ID VARCHAR(20) NOT NULL,
  NAME VARCHAR(20) NOT NULL,
  FOREIGN KEY(LOBBY_ID) REFERENCES LOBBY(ID)
);
